#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauTienVS2._0.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NEWS")]
	public partial class NEWSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMenus(Menus instance);
    partial void UpdateMenus(Menus instance);
    partial void DeleteMenus(Menus instance);
    partial void InsertMenus_NEW(Menus_NEW instance);
    partial void UpdateMenus_NEW(Menus_NEW instance);
    partial void DeleteMenus_NEW(Menus_NEW instance);
    partial void InsertNEWS(NEWS instance);
    partial void UpdateNEWS(NEWS instance);
    partial void DeleteNEWS(NEWS instance);
    partial void InsertPageItem(PageItem instance);
    partial void UpdatePageItem(PageItem instance);
    partial void DeletePageItem(PageItem instance);
    partial void InsertStatistical(Statistical instance);
    partial void UpdateStatistical(Statistical instance);
    partial void DeleteStatistical(Statistical instance);
    partial void InsertSolution(Solution instance);
    partial void UpdateSolution(Solution instance);
    partial void DeleteSolution(Solution instance);
    partial void InsertQuestion(Question instance);
    partial void UpdateQuestion(Question instance);
    partial void DeleteQuestion(Question instance);
    partial void InsertAcount(Acount instance);
    partial void UpdateAcount(Acount instance);
    partial void DeleteAcount(Acount instance);
    #endregion
		
		public NEWSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NEWSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NEWSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NEWSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NEWSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NEWSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Menus> Menus
		{
			get
			{
				return this.GetTable<Menus>();
			}
		}
		
		public System.Data.Linq.Table<Menus_NEW> Menus_NEWs
		{
			get
			{
				return this.GetTable<Menus_NEW>();
			}
		}
		
		public System.Data.Linq.Table<NEWS> NEWS
		{
			get
			{
				return this.GetTable<NEWS>();
			}
		}
		
		public System.Data.Linq.Table<PageItem> PageItems
		{
			get
			{
				return this.GetTable<PageItem>();
			}
		}
		
		public System.Data.Linq.Table<Statistical> Statisticals
		{
			get
			{
				return this.GetTable<Statistical>();
			}
		}
		
		public System.Data.Linq.Table<Solution> Solutions
		{
			get
			{
				return this.GetTable<Solution>();
			}
		}
		
		public System.Data.Linq.Table<Question> Questions
		{
			get
			{
				return this.GetTable<Question>();
			}
		}
		
		public System.Data.Linq.Table<Acount> Acounts
		{
			get
			{
				return this.GetTable<Acount>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menus")]
	public partial class Menus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_MN;
		
		private System.Nullable<long> _Parent;
		
		private System.Nullable<byte> _Pos;
		
		private string _Lable;
		
		private string _UrLink;
		
		private System.Nullable<long> _OrderKey;
		
		private string _Username;
		
		private string _Usertest;
		
		private System.Nullable<bool> _Hide;
		
		private EntitySet<PageItem> _PageItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MNChanging(long value);
    partial void OnID_MNChanged();
    partial void OnParentChanging(System.Nullable<long> value);
    partial void OnParentChanged();
    partial void OnPosChanging(System.Nullable<byte> value);
    partial void OnPosChanged();
    partial void OnLableChanging(string value);
    partial void OnLableChanged();
    partial void OnUrLinkChanging(string value);
    partial void OnUrLinkChanged();
    partial void OnOrderKeyChanging(System.Nullable<long> value);
    partial void OnOrderKeyChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnUsertestChanging(string value);
    partial void OnUsertestChanged();
    partial void OnHideChanging(System.Nullable<bool> value);
    partial void OnHideChanged();
    #endregion
		
		public Menus()
		{
			this._PageItems = new EntitySet<PageItem>(new Action<PageItem>(this.attach_PageItems), new Action<PageItem>(this.detach_PageItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MN", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_MN
		{
			get
			{
				return this._ID_MN;
			}
			set
			{
				if ((this._ID_MN != value))
				{
					this.OnID_MNChanging(value);
					this.SendPropertyChanging();
					this._ID_MN = value;
					this.SendPropertyChanged("ID_MN");
					this.OnID_MNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="BigInt")]
		public System.Nullable<long> Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this.OnParentChanging(value);
					this.SendPropertyChanging();
					this._Parent = value;
					this.SendPropertyChanged("Parent");
					this.OnParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pos", DbType="TinyInt")]
		public System.Nullable<byte> Pos
		{
			get
			{
				return this._Pos;
			}
			set
			{
				if ((this._Pos != value))
				{
					this.OnPosChanging(value);
					this.SendPropertyChanging();
					this._Pos = value;
					this.SendPropertyChanged("Pos");
					this.OnPosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lable", DbType="NVarChar(200)")]
		public string Lable
		{
			get
			{
				return this._Lable;
			}
			set
			{
				if ((this._Lable != value))
				{
					this.OnLableChanging(value);
					this.SendPropertyChanging();
					this._Lable = value;
					this.SendPropertyChanged("Lable");
					this.OnLableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrLink", DbType="VarChar(200)")]
		public string UrLink
		{
			get
			{
				return this._UrLink;
			}
			set
			{
				if ((this._UrLink != value))
				{
					this.OnUrLinkChanging(value);
					this.SendPropertyChanging();
					this._UrLink = value;
					this.SendPropertyChanged("UrLink");
					this.OnUrLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="BigInt")]
		public System.Nullable<long> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usertest", DbType="VarChar(50)")]
		public string Usertest
		{
			get
			{
				return this._Usertest;
			}
			set
			{
				if ((this._Usertest != value))
				{
					this.OnUsertestChanging(value);
					this.SendPropertyChanging();
					this._Usertest = value;
					this.SendPropertyChanged("Usertest");
					this.OnUsertestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hide", DbType="Bit")]
		public System.Nullable<bool> Hide
		{
			get
			{
				return this._Hide;
			}
			set
			{
				if ((this._Hide != value))
				{
					this.OnHideChanging(value);
					this.SendPropertyChanging();
					this._Hide = value;
					this.SendPropertyChanged("Hide");
					this.OnHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_PageItem", Storage="_PageItems", ThisKey="ID_MN", OtherKey="ID_MN")]
		public EntitySet<PageItem> PageItems
		{
			get
			{
				return this._PageItems;
			}
			set
			{
				this._PageItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PageItems(PageItem entity)
		{
			this.SendPropertyChanging();
			entity.Menus = this;
		}
		
		private void detach_PageItems(PageItem entity)
		{
			this.SendPropertyChanging();
			entity.Menus = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menus_NEWS")]
	public partial class Menus_NEW : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_MN_NEW;
		
		private System.Nullable<long> _Parent;
		
		private System.Nullable<byte> _Pos;
		
		private string _Lable;
		
		private string _UrLink;
		
		private System.Nullable<long> _OrderKey;
		
		private string _Username;
		
		private System.Nullable<bool> _Hide;
		
		private EntitySet<NEWS> _NEWS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MN_NEWChanging(long value);
    partial void OnID_MN_NEWChanged();
    partial void OnParentChanging(System.Nullable<long> value);
    partial void OnParentChanged();
    partial void OnPosChanging(System.Nullable<byte> value);
    partial void OnPosChanged();
    partial void OnLableChanging(string value);
    partial void OnLableChanged();
    partial void OnUrLinkChanging(string value);
    partial void OnUrLinkChanged();
    partial void OnOrderKeyChanging(System.Nullable<long> value);
    partial void OnOrderKeyChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnHideChanging(System.Nullable<bool> value);
    partial void OnHideChanged();
    #endregion
		
		public Menus_NEW()
		{
			this._NEWS = new EntitySet<NEWS>(new Action<NEWS>(this.attach_NEWS), new Action<NEWS>(this.detach_NEWS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MN_NEW", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_MN_NEW
		{
			get
			{
				return this._ID_MN_NEW;
			}
			set
			{
				if ((this._ID_MN_NEW != value))
				{
					this.OnID_MN_NEWChanging(value);
					this.SendPropertyChanging();
					this._ID_MN_NEW = value;
					this.SendPropertyChanged("ID_MN_NEW");
					this.OnID_MN_NEWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="BigInt")]
		public System.Nullable<long> Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this.OnParentChanging(value);
					this.SendPropertyChanging();
					this._Parent = value;
					this.SendPropertyChanged("Parent");
					this.OnParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pos", DbType="TinyInt")]
		public System.Nullable<byte> Pos
		{
			get
			{
				return this._Pos;
			}
			set
			{
				if ((this._Pos != value))
				{
					this.OnPosChanging(value);
					this.SendPropertyChanging();
					this._Pos = value;
					this.SendPropertyChanged("Pos");
					this.OnPosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lable", DbType="NVarChar(200)")]
		public string Lable
		{
			get
			{
				return this._Lable;
			}
			set
			{
				if ((this._Lable != value))
				{
					this.OnLableChanging(value);
					this.SendPropertyChanging();
					this._Lable = value;
					this.SendPropertyChanged("Lable");
					this.OnLableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrLink", DbType="VarChar(200)")]
		public string UrLink
		{
			get
			{
				return this._UrLink;
			}
			set
			{
				if ((this._UrLink != value))
				{
					this.OnUrLinkChanging(value);
					this.SendPropertyChanging();
					this._UrLink = value;
					this.SendPropertyChanged("UrLink");
					this.OnUrLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="BigInt")]
		public System.Nullable<long> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hide", DbType="Bit")]
		public System.Nullable<bool> Hide
		{
			get
			{
				return this._Hide;
			}
			set
			{
				if ((this._Hide != value))
				{
					this.OnHideChanging(value);
					this.SendPropertyChanging();
					this._Hide = value;
					this.SendPropertyChanged("Hide");
					this.OnHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_NEW_NEWS", Storage="_NEWS", ThisKey="ID_MN_NEW", OtherKey="ID_MN_NEW")]
		public EntitySet<NEWS> NEWS
		{
			get
			{
				return this._NEWS;
			}
			set
			{
				this._NEWS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NEWS(NEWS entity)
		{
			this.SendPropertyChanging();
			entity.Menus_NEW = this;
		}
		
		private void detach_NEWS(NEWS entity)
		{
			this.SendPropertyChanging();
			entity.Menus_NEW = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NEWS")]
	public partial class NEWS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_NEW;
		
		private System.Nullable<long> _ID_MN_NEW;
		
		private string _Title;
		
		private string _Sumary;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _CreaData;
		
		private System.Nullable<System.DateTime> _ModiData;
		
		private System.Nullable<long> _OrderKey;
		
		private string _Username;
		
		private System.Nullable<bool> _Hide;
		
		private string _image;
		
		private EntityRef<Menus_NEW> _Menus_NEW;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NEWChanging(long value);
    partial void OnID_NEWChanged();
    partial void OnID_MN_NEWChanging(System.Nullable<long> value);
    partial void OnID_MN_NEWChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnSumaryChanging(string value);
    partial void OnSumaryChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnCreaDataChanging(System.Nullable<System.DateTime> value);
    partial void OnCreaDataChanged();
    partial void OnModiDataChanging(System.Nullable<System.DateTime> value);
    partial void OnModiDataChanged();
    partial void OnOrderKeyChanging(System.Nullable<long> value);
    partial void OnOrderKeyChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnHideChanging(System.Nullable<bool> value);
    partial void OnHideChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    #endregion
		
		public NEWS()
		{
			this._Menus_NEW = default(EntityRef<Menus_NEW>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NEW", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_NEW
		{
			get
			{
				return this._ID_NEW;
			}
			set
			{
				if ((this._ID_NEW != value))
				{
					this.OnID_NEWChanging(value);
					this.SendPropertyChanging();
					this._ID_NEW = value;
					this.SendPropertyChanged("ID_NEW");
					this.OnID_NEWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MN_NEW", DbType="BigInt")]
		public System.Nullable<long> ID_MN_NEW
		{
			get
			{
				return this._ID_MN_NEW;
			}
			set
			{
				if ((this._ID_MN_NEW != value))
				{
					if (this._Menus_NEW.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MN_NEWChanging(value);
					this.SendPropertyChanging();
					this._ID_MN_NEW = value;
					this.SendPropertyChanged("ID_MN_NEW");
					this.OnID_MN_NEWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sumary", DbType="NVarChar(500)")]
		public string Sumary
		{
			get
			{
				return this._Sumary;
			}
			set
			{
				if ((this._Sumary != value))
				{
					this.OnSumaryChanging(value);
					this.SendPropertyChanging();
					this._Sumary = value;
					this.SendPropertyChanged("Sumary");
					this.OnSumaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreaData", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CreaData
		{
			get
			{
				return this._CreaData;
			}
			set
			{
				if ((this._CreaData != value))
				{
					this.OnCreaDataChanging(value);
					this.SendPropertyChanging();
					this._CreaData = value;
					this.SendPropertyChanged("CreaData");
					this.OnCreaDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModiData", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ModiData
		{
			get
			{
				return this._ModiData;
			}
			set
			{
				if ((this._ModiData != value))
				{
					this.OnModiDataChanging(value);
					this.SendPropertyChanging();
					this._ModiData = value;
					this.SendPropertyChanged("ModiData");
					this.OnModiDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="BigInt")]
		public System.Nullable<long> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hide", DbType="Bit")]
		public System.Nullable<bool> Hide
		{
			get
			{
				return this._Hide;
			}
			set
			{
				if ((this._Hide != value))
				{
					this.OnHideChanging(value);
					this.SendPropertyChanging();
					this._Hide = value;
					this.SendPropertyChanged("Hide");
					this.OnHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(100)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_NEW_NEWS", Storage="_Menus_NEW", ThisKey="ID_MN_NEW", OtherKey="ID_MN_NEW", IsForeignKey=true, DeleteRule="CASCADE")]
		public Menus_NEW Menus_NEW
		{
			get
			{
				return this._Menus_NEW.Entity;
			}
			set
			{
				Menus_NEW previousValue = this._Menus_NEW.Entity;
				if (((previousValue != value) 
							|| (this._Menus_NEW.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menus_NEW.Entity = null;
						previousValue.NEWS.Remove(this);
					}
					this._Menus_NEW.Entity = value;
					if ((value != null))
					{
						value.NEWS.Add(this);
						this._ID_MN_NEW = value.ID_MN_NEW;
					}
					else
					{
						this._ID_MN_NEW = default(Nullable<long>);
					}
					this.SendPropertyChanged("Menus_NEW");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PageItems")]
	public partial class PageItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_P;
		
		private System.Nullable<long> _ID_MN;
		
		private string _Title;
		
		private string _Sumary;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _CreaData;
		
		private System.Nullable<System.DateTime> _ModiDate;
		
		private System.Nullable<long> _OrderKey;
		
		private string _Username;
		
		private string _UserTest;
		
		private System.Nullable<bool> _Hide;
		
		private string _ID_File;
		
		private string _Name_File;
		
		private System.Data.Linq.Binary _QRcode;
		
		private EntityRef<Menus> _Menus;
		
		private EntityRef<Acount> _Acount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PChanging(long value);
    partial void OnID_PChanged();
    partial void OnID_MNChanging(System.Nullable<long> value);
    partial void OnID_MNChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnSumaryChanging(string value);
    partial void OnSumaryChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnCreaDataChanging(System.Nullable<System.DateTime> value);
    partial void OnCreaDataChanged();
    partial void OnModiDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModiDateChanged();
    partial void OnOrderKeyChanging(System.Nullable<long> value);
    partial void OnOrderKeyChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnUserTestChanging(string value);
    partial void OnUserTestChanged();
    partial void OnHideChanging(System.Nullable<bool> value);
    partial void OnHideChanged();
    partial void OnID_FileChanging(string value);
    partial void OnID_FileChanged();
    partial void OnName_FileChanging(string value);
    partial void OnName_FileChanged();
    partial void OnQRcodeChanging(System.Data.Linq.Binary value);
    partial void OnQRcodeChanged();
    #endregion
		
		public PageItem()
		{
			this._Menus = default(EntityRef<Menus>);
			this._Acount = default(EntityRef<Acount>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_P", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_P
		{
			get
			{
				return this._ID_P;
			}
			set
			{
				if ((this._ID_P != value))
				{
					this.OnID_PChanging(value);
					this.SendPropertyChanging();
					this._ID_P = value;
					this.SendPropertyChanged("ID_P");
					this.OnID_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MN", DbType="BigInt")]
		public System.Nullable<long> ID_MN
		{
			get
			{
				return this._ID_MN;
			}
			set
			{
				if ((this._ID_MN != value))
				{
					if (this._Menus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MNChanging(value);
					this.SendPropertyChanging();
					this._ID_MN = value;
					this.SendPropertyChanged("ID_MN");
					this.OnID_MNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sumary", DbType="NVarChar(500)")]
		public string Sumary
		{
			get
			{
				return this._Sumary;
			}
			set
			{
				if ((this._Sumary != value))
				{
					this.OnSumaryChanging(value);
					this.SendPropertyChanging();
					this._Sumary = value;
					this.SendPropertyChanged("Sumary");
					this.OnSumaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreaData", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CreaData
		{
			get
			{
				return this._CreaData;
			}
			set
			{
				if ((this._CreaData != value))
				{
					this.OnCreaDataChanging(value);
					this.SendPropertyChanging();
					this._CreaData = value;
					this.SendPropertyChanged("CreaData");
					this.OnCreaDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModiDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ModiDate
		{
			get
			{
				return this._ModiDate;
			}
			set
			{
				if ((this._ModiDate != value))
				{
					this.OnModiDateChanging(value);
					this.SendPropertyChanging();
					this._ModiDate = value;
					this.SendPropertyChanged("ModiDate");
					this.OnModiDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="BigInt")]
		public System.Nullable<long> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._Acount.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTest", DbType="VarChar(50)")]
		public string UserTest
		{
			get
			{
				return this._UserTest;
			}
			set
			{
				if ((this._UserTest != value))
				{
					this.OnUserTestChanging(value);
					this.SendPropertyChanging();
					this._UserTest = value;
					this.SendPropertyChanged("UserTest");
					this.OnUserTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hide", DbType="Bit")]
		public System.Nullable<bool> Hide
		{
			get
			{
				return this._Hide;
			}
			set
			{
				if ((this._Hide != value))
				{
					this.OnHideChanging(value);
					this.SendPropertyChanging();
					this._Hide = value;
					this.SendPropertyChanged("Hide");
					this.OnHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_File", DbType="VarChar(100)")]
		public string ID_File
		{
			get
			{
				return this._ID_File;
			}
			set
			{
				if ((this._ID_File != value))
				{
					this.OnID_FileChanging(value);
					this.SendPropertyChanging();
					this._ID_File = value;
					this.SendPropertyChanged("ID_File");
					this.OnID_FileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_File", DbType="NVarChar(256)")]
		public string Name_File
		{
			get
			{
				return this._Name_File;
			}
			set
			{
				if ((this._Name_File != value))
				{
					this.OnName_FileChanging(value);
					this.SendPropertyChanging();
					this._Name_File = value;
					this.SendPropertyChanged("Name_File");
					this.OnName_FileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QRcode", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary QRcode
		{
			get
			{
				return this._QRcode;
			}
			set
			{
				if ((this._QRcode != value))
				{
					this.OnQRcodeChanging(value);
					this.SendPropertyChanging();
					this._QRcode = value;
					this.SendPropertyChanged("QRcode");
					this.OnQRcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_PageItem", Storage="_Menus", ThisKey="ID_MN", OtherKey="ID_MN", IsForeignKey=true, DeleteRule="CASCADE")]
		public Menus Menus
		{
			get
			{
				return this._Menus.Entity;
			}
			set
			{
				Menus previousValue = this._Menus.Entity;
				if (((previousValue != value) 
							|| (this._Menus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menus.Entity = null;
						previousValue.PageItems.Remove(this);
					}
					this._Menus.Entity = value;
					if ((value != null))
					{
						value.PageItems.Add(this);
						this._ID_MN = value.ID_MN;
					}
					else
					{
						this._ID_MN = default(Nullable<long>);
					}
					this.SendPropertyChanged("Menus");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Acount_PageItem", Storage="_Acount", ThisKey="Username", OtherKey="Username", IsForeignKey=true, DeleteRule="CASCADE")]
		public Acount Acount
		{
			get
			{
				return this._Acount.Entity;
			}
			set
			{
				Acount previousValue = this._Acount.Entity;
				if (((previousValue != value) 
							|| (this._Acount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Acount.Entity = null;
						previousValue.PageItems.Remove(this);
					}
					this._Acount.Entity = value;
					if ((value != null))
					{
						value.PageItems.Add(this);
						this._Username = value.Username;
					}
					else
					{
						this._Username = default(string);
					}
					this.SendPropertyChanged("Acount");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Statistical")]
	public partial class Statistical : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_TF;
		
		private System.Nullable<int> _Traffic;
		
		private System.Nullable<int> _Online;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TFChanging(long value);
    partial void OnID_TFChanged();
    partial void OnTrafficChanging(System.Nullable<int> value);
    partial void OnTrafficChanged();
    partial void OnOnlineChanging(System.Nullable<int> value);
    partial void OnOnlineChanged();
    #endregion
		
		public Statistical()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TF", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_TF
		{
			get
			{
				return this._ID_TF;
			}
			set
			{
				if ((this._ID_TF != value))
				{
					this.OnID_TFChanging(value);
					this.SendPropertyChanging();
					this._ID_TF = value;
					this.SendPropertyChanged("ID_TF");
					this.OnID_TFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Traffic", DbType="Int")]
		public System.Nullable<int> Traffic
		{
			get
			{
				return this._Traffic;
			}
			set
			{
				if ((this._Traffic != value))
				{
					this.OnTrafficChanging(value);
					this.SendPropertyChanging();
					this._Traffic = value;
					this.SendPropertyChanged("Traffic");
					this.OnTrafficChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Online", DbType="Int")]
		public System.Nullable<int> Online
		{
			get
			{
				return this._Online;
			}
			set
			{
				if ((this._Online != value))
				{
					this.OnOnlineChanging(value);
					this.SendPropertyChanging();
					this._Online = value;
					this.SendPropertyChanged("Online");
					this.OnOnlineChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Solutions")]
	public partial class Solution : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_S;
		
		private System.Nullable<long> _ID_Q;
		
		private string _Reply;
		
		private string _Username;
		
		private string _FullName;
		
		private string _Avarta;
		
		private System.Nullable<System.DateTime> _CreaData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SChanging(long value);
    partial void OnID_SChanged();
    partial void OnID_QChanging(System.Nullable<long> value);
    partial void OnID_QChanged();
    partial void OnReplyChanging(string value);
    partial void OnReplyChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnAvartaChanging(string value);
    partial void OnAvartaChanged();
    partial void OnCreaDataChanging(System.Nullable<System.DateTime> value);
    partial void OnCreaDataChanged();
    #endregion
		
		public Solution()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_S", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_S
		{
			get
			{
				return this._ID_S;
			}
			set
			{
				if ((this._ID_S != value))
				{
					this.OnID_SChanging(value);
					this.SendPropertyChanging();
					this._ID_S = value;
					this.SendPropertyChanged("ID_S");
					this.OnID_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Q", DbType="BigInt")]
		public System.Nullable<long> ID_Q
		{
			get
			{
				return this._ID_Q;
			}
			set
			{
				if ((this._ID_Q != value))
				{
					this.OnID_QChanging(value);
					this.SendPropertyChanging();
					this._ID_Q = value;
					this.SendPropertyChanged("ID_Q");
					this.OnID_QChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reply", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Reply
		{
			get
			{
				return this._Reply;
			}
			set
			{
				if ((this._Reply != value))
				{
					this.OnReplyChanging(value);
					this.SendPropertyChanging();
					this._Reply = value;
					this.SendPropertyChanged("Reply");
					this.OnReplyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(255)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(256)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avarta", DbType="VarChar(256)")]
		public string Avarta
		{
			get
			{
				return this._Avarta;
			}
			set
			{
				if ((this._Avarta != value))
				{
					this.OnAvartaChanging(value);
					this.SendPropertyChanging();
					this._Avarta = value;
					this.SendPropertyChanged("Avarta");
					this.OnAvartaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreaData", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CreaData
		{
			get
			{
				return this._CreaData;
			}
			set
			{
				if ((this._CreaData != value))
				{
					this.OnCreaDataChanging(value);
					this.SendPropertyChanging();
					this._CreaData = value;
					this.SendPropertyChanged("CreaData");
					this.OnCreaDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Questions")]
	public partial class Question : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_Q;
		
		private System.Nullable<int> _Parent;
		
		private string _Title;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _CreaData;
		
		private System.Nullable<System.DateTime> _ModiData;
		
		private string _Username;
		
		private System.Nullable<bool> _Hide;
		
		private string _fullName;
		
		private string _Avatar;
		
		private string _Users_Liked;
		
		private System.Nullable<int> _Liked;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_QChanging(long value);
    partial void OnID_QChanged();
    partial void OnParentChanging(System.Nullable<int> value);
    partial void OnParentChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnCreaDataChanging(System.Nullable<System.DateTime> value);
    partial void OnCreaDataChanged();
    partial void OnModiDataChanging(System.Nullable<System.DateTime> value);
    partial void OnModiDataChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnHideChanging(System.Nullable<bool> value);
    partial void OnHideChanged();
    partial void OnfullNameChanging(string value);
    partial void OnfullNameChanged();
    partial void OnAvatarChanging(string value);
    partial void OnAvatarChanged();
    partial void OnUsers_LikedChanging(string value);
    partial void OnUsers_LikedChanged();
    partial void OnLikedChanging(System.Nullable<int> value);
    partial void OnLikedChanged();
    #endregion
		
		public Question()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Q", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_Q
		{
			get
			{
				return this._ID_Q;
			}
			set
			{
				if ((this._ID_Q != value))
				{
					this.OnID_QChanging(value);
					this.SendPropertyChanging();
					this._ID_Q = value;
					this.SendPropertyChanged("ID_Q");
					this.OnID_QChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="Int")]
		public System.Nullable<int> Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this.OnParentChanging(value);
					this.SendPropertyChanging();
					this._Parent = value;
					this.SendPropertyChanged("Parent");
					this.OnParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(255)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreaData", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CreaData
		{
			get
			{
				return this._CreaData;
			}
			set
			{
				if ((this._CreaData != value))
				{
					this.OnCreaDataChanging(value);
					this.SendPropertyChanging();
					this._CreaData = value;
					this.SendPropertyChanged("CreaData");
					this.OnCreaDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModiData", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ModiData
		{
			get
			{
				return this._ModiData;
			}
			set
			{
				if ((this._ModiData != value))
				{
					this.OnModiDataChanging(value);
					this.SendPropertyChanging();
					this._ModiData = value;
					this.SendPropertyChanged("ModiData");
					this.OnModiDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hide", DbType="Bit")]
		public System.Nullable<bool> Hide
		{
			get
			{
				return this._Hide;
			}
			set
			{
				if ((this._Hide != value))
				{
					this.OnHideChanging(value);
					this.SendPropertyChanging();
					this._Hide = value;
					this.SendPropertyChanged("Hide");
					this.OnHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(100)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this.OnfullNameChanging(value);
					this.SendPropertyChanging();
					this._fullName = value;
					this.SendPropertyChanged("fullName");
					this.OnfullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="NVarChar(256)")]
		public string Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Users_Liked", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Users_Liked
		{
			get
			{
				return this._Users_Liked;
			}
			set
			{
				if ((this._Users_Liked != value))
				{
					this.OnUsers_LikedChanging(value);
					this.SendPropertyChanging();
					this._Users_Liked = value;
					this.SendPropertyChanged("Users_Liked");
					this.OnUsers_LikedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liked", DbType="Int")]
		public System.Nullable<int> Liked
		{
			get
			{
				return this._Liked;
			}
			set
			{
				if ((this._Liked != value))
				{
					this.OnLikedChanging(value);
					this.SendPropertyChanging();
					this._Liked = value;
					this.SendPropertyChanged("Liked");
					this.OnLikedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Acounts")]
	public partial class Acount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private long _ID_User;
		
		private string _Password;
		
		private string _Fullname;
		
		private System.Nullable<byte> _Permission;
		
		private string _Email;
		
		private System.Nullable<bool> _Lock;
		
		private System.Nullable<bool> _Active;
		
		private string _Avatar;
		
		private System.Nullable<int> _Likes;
		
		private System.Nullable<int> _Cups;
		
		private System.Nullable<int> _Dislikes;
		
		private string _Introduce_Yourself;
		
		private System.Nullable<bool> _Confirm;
		
		private System.Nullable<System.DateTime> _Join;
		
		private EntitySet<PageItem> _PageItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnID_UserChanging(long value);
    partial void OnID_UserChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFullnameChanging(string value);
    partial void OnFullnameChanged();
    partial void OnPermissionChanging(System.Nullable<byte> value);
    partial void OnPermissionChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLockChanging(System.Nullable<bool> value);
    partial void OnLockChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnAvatarChanging(string value);
    partial void OnAvatarChanged();
    partial void OnLikesChanging(System.Nullable<int> value);
    partial void OnLikesChanged();
    partial void OnCupsChanging(System.Nullable<int> value);
    partial void OnCupsChanged();
    partial void OnDislikesChanging(System.Nullable<int> value);
    partial void OnDislikesChanged();
    partial void OnIntroduce_YourselfChanging(string value);
    partial void OnIntroduce_YourselfChanged();
    partial void OnConfirmChanging(System.Nullable<bool> value);
    partial void OnConfirmChanged();
    partial void OnJoinChanging(System.Nullable<System.DateTime> value);
    partial void OnJoinChanged();
    #endregion
		
		public Acount()
		{
			this._PageItems = new EntitySet<PageItem>(new Action<PageItem>(this.attach_PageItems), new Action<PageItem>(this.detach_PageItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_User", DbType="BigInt NOT NULL")]
		public long ID_User
		{
			get
			{
				return this._ID_User;
			}
			set
			{
				if ((this._ID_User != value))
				{
					this.OnID_UserChanging(value);
					this.SendPropertyChanging();
					this._ID_User = value;
					this.SendPropertyChanged("ID_User");
					this.OnID_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(100)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this.OnFullnameChanging(value);
					this.SendPropertyChanging();
					this._Fullname = value;
					this.SendPropertyChanged("Fullname");
					this.OnFullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="TinyInt")]
		public System.Nullable<byte> Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this.OnPermissionChanging(value);
					this.SendPropertyChanging();
					this._Permission = value;
					this.SendPropertyChanged("Permission");
					this.OnPermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lock", DbType="Bit")]
		public System.Nullable<bool> Lock
		{
			get
			{
				return this._Lock;
			}
			set
			{
				if ((this._Lock != value))
				{
					this.OnLockChanging(value);
					this.SendPropertyChanging();
					this._Lock = value;
					this.SendPropertyChanged("Lock");
					this.OnLockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="VarChar(50)")]
		public string Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Likes", DbType="Int")]
		public System.Nullable<int> Likes
		{
			get
			{
				return this._Likes;
			}
			set
			{
				if ((this._Likes != value))
				{
					this.OnLikesChanging(value);
					this.SendPropertyChanging();
					this._Likes = value;
					this.SendPropertyChanged("Likes");
					this.OnLikesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cups", DbType="Int")]
		public System.Nullable<int> Cups
		{
			get
			{
				return this._Cups;
			}
			set
			{
				if ((this._Cups != value))
				{
					this.OnCupsChanging(value);
					this.SendPropertyChanging();
					this._Cups = value;
					this.SendPropertyChanged("Cups");
					this.OnCupsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dislikes", DbType="Int")]
		public System.Nullable<int> Dislikes
		{
			get
			{
				return this._Dislikes;
			}
			set
			{
				if ((this._Dislikes != value))
				{
					this.OnDislikesChanging(value);
					this.SendPropertyChanging();
					this._Dislikes = value;
					this.SendPropertyChanged("Dislikes");
					this.OnDislikesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Introduce_Yourself", DbType="NVarChar(256)")]
		public string Introduce_Yourself
		{
			get
			{
				return this._Introduce_Yourself;
			}
			set
			{
				if ((this._Introduce_Yourself != value))
				{
					this.OnIntroduce_YourselfChanging(value);
					this.SendPropertyChanging();
					this._Introduce_Yourself = value;
					this.SendPropertyChanged("Introduce_Yourself");
					this.OnIntroduce_YourselfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Confirm]", Storage="_Confirm", DbType="Bit")]
		public System.Nullable<bool> Confirm
		{
			get
			{
				return this._Confirm;
			}
			set
			{
				if ((this._Confirm != value))
				{
					this.OnConfirmChanging(value);
					this.SendPropertyChanging();
					this._Confirm = value;
					this.SendPropertyChanged("Confirm");
					this.OnConfirmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Join]", Storage="_Join", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Join
		{
			get
			{
				return this._Join;
			}
			set
			{
				if ((this._Join != value))
				{
					this.OnJoinChanging(value);
					this.SendPropertyChanging();
					this._Join = value;
					this.SendPropertyChanged("Join");
					this.OnJoinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Acount_PageItem", Storage="_PageItems", ThisKey="Username", OtherKey="Username")]
		public EntitySet<PageItem> PageItems
		{
			get
			{
				return this._PageItems;
			}
			set
			{
				this._PageItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PageItems(PageItem entity)
		{
			this.SendPropertyChanging();
			entity.Acount = this;
		}
		
		private void detach_PageItems(PageItem entity)
		{
			this.SendPropertyChanging();
			entity.Acount = null;
		}
	}
}
#pragma warning restore 1591
